services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend-ferroviario-container
    volumes:
      - ..:/ferroviario-backend:cached
    ports:
      - "8500:8500"
    command: [ "sleep", "infinity" ]
    networks:
      - dev-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: backend-ferroviario-postgres
    restart: always
    env_file:
      - ../backend/.env
    ports:
      - "5451:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-data: {}
